### ISSUE TITLE
Is there anyway for this code to be upgraded to work in 2.8 / 2.9.  

### ISSUE THREAD

**Issue by stillpointx** [ly29/GenericNote#1]
Is there anyway for this code can be upgraded to work in 2.8 / 2.9?

I found out that having a node that includes notes about each separate object created in a scene very helpful.  (Each object is created with an equation and can be several lines long which after 3 weeks I completely just forget.)

https://ijk4de.gitlab.io/3d/index.html

I'm getting an the error:
```
Traceback (most recent call last):
  File "/snap/blender/51/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/rt/.config/blender/2.91/scripts/addons/generic_note.py", line 41, in <module>
    from nodeitems_builtins import (CompositorNodeCategory,
ImportError: cannot import name 'ShaderNewNodeCategory' from 'nodeitems_builtins' (/snap/blender/51/2.91/scripts/startup/nodeitems_builtins.py)
```

**Comment by ly29** [comment]
I’m sorry for replying late. 

I am quite sure it could be done. What seems to fail is the registering on menus but probably more things are broken.

I will not have time to do it however, mostly because I’m not using it myself anymore

**Comment by frankk74** [comment]
Any chance that you could add broken in >2,7 on your main readme.md here? It seems 2 of us have be unable to make it  work. Your original work is appreciated. Thank you!
